version: "3"

services:
  ss:
    image: ahui/sslocal
    restart: always
    ports:
    - ${SS_HOST}:${SS_LISTEN_PORT}:${SS_LISTEN_PORT}
    command: ["-k", "${SS_KEY}", "-s", "kcp", "-p", "8700", "-l", "${SS_LISTEN_PORT}"]
  kcp:
    image: xtaci/kcptun
    restart: always
    command: ["client", "-l", ":8700", "-r", "${KCP_SERVER_TARGET}", "--key", "${KCP_KEY}", "--quiet"]
  # ss-direct:
  #   image: ahui/sslocal
  #   restart: always
  #   ports:
  #     - 1090:1090
  #   command: ["-k", "THEKEY", "-b", "0.0.0.0", "-s", "abcd:abcd:0:abcd::abcd:abcd", "-p", "33000", "-l", "1090"]
